// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EventMaker")>]
[<assembly: AssemblyProductAttribute("EventMaker")>]
[<assembly: AssemblyVersionAttribute("1.9999.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.9999.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EventMaker"
    let [<Literal>] AssemblyProduct = "EventMaker"
    let [<Literal>] AssemblyVersion = "1.9999.0.0"
    let [<Literal>] AssemblyFileVersion = "1.9999.0.0"
